version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql-alexa-local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: alexa_devices
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alexa-smart-home-local
    restart: unless-stopped
    env_file:
      - .env.local
    depends_on:
      - mysql
    ports:
      - "3000:3000"

    # IMPORTANTE:
    # No futuro, quando você for colocar HTTPS com Nginx/Caddy/Traefik,
    # você provavelmente VAI TIRAR esse "ports: 3000:3000" e deixar o proxy
    # expor as portas 80/443 para fora. A app continua ouvindo na 3000 interna.

volumes:
  mysql_data:
